#ifndef CONFIG_H
#define CONFIG_H

#define MAX_TCP_CONNECTION 10
#define LOCAL_PORT 3333
#define TARGET_PORT 3334

#define LOCAL_IP "0.0.0.0"
#define TARGET_IP "192.168.43.16"

#define LOCAL_GYROSCOPE_PORT 3333
#define TARGET_GYROSCOPE_PORT 3334

#define CAMERA_FRAME_WIDTH 640
#define CAMERA_FRAME_HEIGHT 480
#define CAMERA_FRAME_TYPE CV_8UC3
#define CAMERA_FRAME_ELEM_SIZE 3

//modules name
#define MAIN_MODULE "MAIN_MODULE"
#define REMOTE_CONTROLLER_MODULE "REMOTE_CONTROLLER_MODULE"
#define CAMERA_MODULE "CAMERA_MODULE"
#define CAMERA_TRANSMITTER_MODULE "CAMERA_TRANSMITTER_MODULE"
#define GYROSCOPE_RECEIVER_MODULE "GYROSCOPE_RECEIVER_MODULE"
#define MOTOR_CONTROLLER_MODULE "MOTOR_CONTROLLER_MODULE"

#endif
